[package]
name = "develop_binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vfs = "0.12.0"
spritebot_storage = { path = "../spritebot_storage" }